on:
  push:

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build container image
      run: |
        docker build \
        --tag ghcr.io/cp6/servyrun:$(echo $GITHUB_SHA | head -c7) \
        --tag ghcr.io/cp6/servyrun:latest \
        .
    - name: Container registry login
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      
    - name: Push image to GHCR
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/cp6/servyrun:$(echo $GITHUB_SHA | head -c7)
        docker push ghcr.io/cp6/servyrun:latest
